### ISSUE TITLE
Youtube Api Key ? 

### ISSUE THREAD

**Issue by yusuftask08** [NomNes/vue3-youtube#2]
Where to write youtube api key
? I couldnt ::(

**Comment by yusuftask08** [comment]
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:8081').

**Comment by NomNes** [comment]
You need set `host` attribute: `:host='localhost:8081'`

**Comment by NomNes** [comment]
Are you sure you need api key for IFrame API? Its not data api. Correct me if I'm wrong

**Comment by yusuftask08** [comment]
you are right solved the problem thank you.

**Comment by yusuftask08** [comment]
:)
